### PR TITLE
#36-Added ESRI base styles and updated existing hard coded values

### LINKED ISSUE #36: Esri base styles
I see lots of component-specific CSS updates and hard coded colors. 

Need to get Esri baseline styles added.

### PR DESCRIPTION
**Pull request by anu13297**
Fix #36 

Changes made:

- Added ESRI base styles, spacing, opacity variables.
- Updated the hard coded values to calcite variables in hero,media gallery,quote css files.

Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/overview
- Before: https://main--esri--aemsites.hlx.live/en-us/about/about-esri/overview
- After: https://esri-base-styles--esri--aemsites.hlx.live/en-us/about/about-esri/overview

### CODE REVIEW

**Comment by alexcarol** [comment]
The overview page has mostly dark backgrounds, does most of the site not share these styles? Should we apply them independently to each block?

**Comment by anu13297** [comment]
> The overview page has mostly dark backgrounds, does most of the site not share these styles? Should we apply them independently to each block?

The default color theme of site should be light background which is calcite-mode-light theme. Dark background can be applied to each section/component independently using calcite-mode-dark. 
Any additional updates needed to align with this will be made as part of this task https://github.com/aemsites/esri/issues/34

**Comment by tim-white-esri** [comment]
@alexcarol you should be able to apply the dark mode to `body` and it *should* inherit to everything else.

**Review by tim-white-esri — APPROVED** [review]

**Comment by alexcarol** [comment]
That makes perfect sense, i'll make sure to add that to the importer logic.

**Pull request merged**
