### PR TITLE
feat (global nav): update to cdn-dev for gnav in effort to avoid CORS…

### LINKED ISSUE #9: Integrate live site header + footer
- footer code: https://github.com/aemsites/esri/blob/main/blocks/footer/footer.js
- header code: https://github.com/aemsites/esri/blob/main/blocks/header/header.js

The header and footer code are both the default that comes with the boilerplate the code can be completely rewritten.

### PR DESCRIPTION
**Pull request by tim-white-esri**
… issue. Add Calcite css call.

Fix #9 

Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/overview
- Before: https://main--esri--aemsites.hlx.live/en-us/about/about-esri/overview
- After: https://gn-update--esri--aemsites.hlx.live/en-us/about/about-esri/overview

### CODE REVIEW

**Comment by tim-white-esri** [comment]
Looks like CORS issues still exists. The JSON reference is still `https://www.esri.com/content/experience-fragments/esri-sites/en-us/site-settings/global-navigation-config/2022-nav-config.25.json`

Kishore mentioned we should be able to allow from dev though. 

@stefanalex99 I also added the Calcite CSS file which brings in all of the color variables we use.

**Comment by alexcarol** [comment]
The js you link (https://webapps-cdn-dev.esri.com/CDN/components/global-nav/js/gn.js) doesn't seem to work for me, is it possible that it's only available within the esri network?

**Comment by tim-white-esri** [comment]
Ah, yeah, that is probably locked down. 
@kishoreCikka1 and I will have to think up a solution. I don't really want to recreate the nav because it is complex and tied into other sites. We'll need to find a way around the CORS issue.

**Comment by tim-white-esri** [comment]
Closing. 
Dev is restricted to Esri IPs. 
Will talk with @kishoreCikka1  for other options.

**Pull request closed without merging**
