### PR TITLE
Implement Centered Content Switcher block

### LINKED ISSUE #93: Implement centered-content-switcher block
Original: https://www.esri.com/en-us/about/about-esri/americas

Suggestion: a similar structure to "mosaic reveal" block might be a good idea

image

### PR DESCRIPTION
**Pull request by vladciocoiu**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #93 

Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/americas
- Before: https://main--esri--aemsites.hlx.live/en-us/about/about-esri/americas
- After: https://add-centered-content-switcher--esri--aemsites.hlx.live/en-us/about/about-esri/americas

### CODE REVIEW

**Comment by hanem100k** [comment]
@vciocoiu popup video has different embedding. Is that intended?

image

image

**Comment by vladciocoiu** [comment]
> @vciocoiu popup video has different embedding. Is that intended?

That's weird, it should have looked the same, since `decorateVideoLinks()` gets called for the block. 

Looking into it

**Review by hanem100k — APPROVED** [review]
lgtm

**Comment by alexcarol** [comment]
Looks great! One minor detail on the embed, on hover the "X" should become white:
Live:
image
Branch:
image

**Review by alexcarol — APPROVED** [review]

**Pull request merged**
